---

- name: Apache_httpd | Copy modules to Apache modules folder
  copy:
    src: "{{ item }}"
    dest: "{{ apache_install_dir }}/modules/"
    owner: root
    group: root
    mode: 0755
    remote_src: true
  loop: "{{ apache_modules_so_files }}"
  when: apache_modules_so_files is defined

- name: Apache_httpd | Ensure extra config file and template paths exists
  file:
    path: "{{ apache_config_dir }}/{{ item.path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_filetree:
    - "{{ apache_extra_conf_template_path }}/"
    - "{{ apache_extra_conf_path }}/"
  when: item.state == 'directory'

- name: Apache_httpd | Copy extra apache config files (provided by playbooks)
  copy:
    src: "{{ item.src }}"
    dest: "{{ apache_config_dir }}/{{ item.path }}"
    owner: root
    group: root
    mode: 0755
  with_filetree:
    - "{{ apache_extra_conf_path }}/"
  when: item.state == "file"
  notify: Reload Apache

- name: Apache_httpd | Copy extra apache config templates (provided by playbooks)
  template:
    src: "{{ item.src }}"
    dest: "{{ apache_config_dir }}/{{ item.path | splitext | first }}"
    owner: root
    group: root
    mode: 0755
  with_filetree:
    - "{{ apache_extra_conf_template_path }}/"
  when: item.state == 'file'
  notify: Reload Apache

- name: Apache_httpd | Ensure logs folder exists
  file:
    dest: "{{ apache_logs_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Apache_httpd | Ensure additional config paths exists
  file:
    path: "{{ apache_config_dir }}/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ apache_additional_config_folders }}"

- name: Apache_httpd | Add symlink in sites-enabled
  file:
    src: "{{ apache_config_dir }}/sites-available/{{ item }}.conf"
    dest: "{{ apache_config_dir }}/sites-enabled/{{ item }}.conf"
    owner: root
    group: root
    mode: 0755
    state: link
  with_items:
    - "{{ apache_sites_enabled }}"
  notify: Reload Apache

- name: Apache_httpd | Create virtualhost folders
  file:
    dest: "{{ apache_document_root }}/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ apache_sites_enabled }}"

- name: Apache_httpd | Copy virtualhost files (provided by playbooks)
  copy:
    src: "{{ item.src }}"
    dest: "{{ apache_document_root }}/{{ item.path }}"
    owner: root
    group: root
    mode: 0755
  with_filetree: "{{ apache_virtualhosts_files_path }}/"
  when: item.state == 'file'
  notify: Reload Apache

- name: Apache_httpd | Template rewrites file (provided by playbooks)
  template:
    src: "{{ item }}"
    dest: "{{ apache_rewrites_template_dest_folder }}/{{ item | basename | splitext | first }}"
    owner: root
    group: root
    mode: 0755
  notify: Reload Apache
  with_fileglob: "{{ apache_rewrites_template_src_folder }}/*"
  tags:
    - apache_rewrites

- name: Apache_httpd | Template apache2.service
  template:
    src: apache/service/apache2.service.j2
    dest: /lib/systemd/system/apache2.service
    mode: 0644
  notify: Restart Apache
